const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const ADD_VALUE = "ADD_VALUE";
const STORE_RESULT = "STORE_RESULT";
const DELETE_RESULT = "DELETE_RESULT";

module.exports = {
  INCREMENT,
  DECREMENT,
  ADD_VALUE,
  STORE_RESULT,
  DELETE_RESULT,
};
